### ISSUE TITLE
Ever heard of .gitignore files?

### ISSUE THREAD

**Issue by renhiyama** [orbi8r/godot-minesweeper#1]
Hi Orbitr,

I hope this message finds you well.

I noticed that your recent projects, including your Hacktoberfest submission, have included binary files and dependencies in your Git repository. While I understand that this might be unintentional, it's generally recommended to avoid committing such files.
I suggest exploring .gitignore files. They allow you to specify patterns for files and directories that Git should ignore. This helps keep your repository clean and efficient.
Please consider using .gitignore in your future projects. It's a common practice among developers and can significantly improve your workflow.

Best regards,
Ren

**Comment by orbi8r** [comment]
Hi Ren,

Wow, what a keen eye you have! Thank you for pointing out my "creative" way of managing repositories—I must admit, I was going for a modern art installation of chaos meets binaries.

Your suggestion to explore .gitignore is truly groundbreaking. Who knew such sorcery existed? I’ll be sure to bookmark it under "Things I Should Have Known Three Years Ago." Your concern for my workflow is touching, and I can't wait to unleash this newfound power on my future repositories.

Thanks for taking the time to reach out. Rest assured, my next commits will be pristine, binary-free wonders that you’d be proud to clone.

Warm regards,
Orbi8r (prolly written by ChatGPT)
